### ISSUE TITLE
if we develop an applicaiton in commerical, and sold applicaiton to our client 

### ISSUE THREAD

**Issue by guozhqi** [syncfusion/ej2-vue-ui-components#23]
if we develop an applicaiton in commerical, and sold applicaiton to our client to use with syncfusion components, what is the license price package we could have ?

**Comment by davsyncfusion** [comment]
If the application source will be maintained by you, only your company needs to buy licenses for the number of developers you have on the project. Your client doesn't need to buy licenses if they are just using the application. If your client takes over the source and starts maintaining the application source, they need to buy licenses for the number of developers they have on the project.

**Comment by guozhqi** [comment]
if we develop the application , and this application used as saas, or sold to multiple clients, what is your license policy in detail? and could you kindly offer us an best price? thanks

**Comment by davsyncfusion** [comment]
There is no additional cost for SAAS application. Selling to multiple customers would come under the same system as what I mentioned earlier (Your client doesn't need to buy licenses if they are just using the application. If your client takes over the source and starts maintaining the application source, they need to buy licenses for the number of developers they have on the project.) - could you please contact our sales team using the Contact Us option https://www.syncfusion.com/company/contact-us so that they can give you the best price along with the license policy in details. Thanks.

**Comment by ajithr** [comment]
@guozhqi  We hope your doubts in Syncfusion licensing is clarified in our last update. Please get back to us if you need any further assistance with this.
