### ISSUE TITLE
does sj2 file manager support upload folder?

### ISSUE THREAD

**Issue by tsulatsitamim** [syncfusion/ej2-vue-ui-components#26]

**Comment by SowmiyaPadmanaban** [comment]
Hi Tsulasi,

Thanks for contacting Syncfusion support.

Currently, we have not provided the folder upload support for file manager component. Since, the folder upload support only available in the recent version of chrome and firefox browsers and not completely supported by the other browsers. Due to this inconsistency, we have not provided this support yet. Once the major browsers implemented this HTML5 directory support, we will consider this feature from our end and implement in the file manager component.


Regards,
Sowmiya.P
