### ISSUE TITLE
Globalization error in DateRangePicker Component (TypeError: Cannot convert undefined or null to object)

### ISSUE THREAD

**Issue by erhansaydam** [syncfusion/ej2-vue-ui-components#38]
Hello,

I would like to use Turkish set for the DateRangePicker Component. I followed the instructions written on the documentation https://ej2.syncfusion.com/vue/documentation/daterangepicker/globalization/
However I got the error:

_Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at DateRangePicker.CalendarBase.getCultureValues (calendar.js?2f9d:278)_
 ```
/*calendar.js?2f9d:278*/
for (var _i = 0, _a = Object.keys(cldrObj); _i < _a.length; _i++) {
            var obj = _a[_i];
            culShortNames.push(getValue(obj, cldrObj));
        }
```
My code is as follows:

```
<template>
...<ejs-daterangepicker id="daterangepicker"  locale="tr" 
             :min="minTarih"></ejs-daterangepicker>...
</template>
<script>
  import "@syncfusion/ej2-vue-calendars/styles/bootstrap4.css";
  import "@syncfusion/ej2-vue-calendars/styles/daterangepicker/bootstrap4.css";
  import "@syncfusion/ej2-vue-inputs/styles/bootstrap4.css";
  import "@syncfusion/ej2-vue-inputs/styles/input/bootstrap4.css";
  import Vue from 'vue';
  import {DateRangePickerPlugin} from '@syncfusion/ej2-vue-calendars';
  import {loadCldr, L10n} from '@syncfusion/ej2-base';
  import numberingSystems from 'cldr-data/supplemental/numberingSystems.json';
  import gregorian from 'cldr-data/main/tr/ca-gregorian.json';
  import numbers from 'cldr-data/main/tr/numbers.json';
  import timeZoneNames from 'cldr-data/main/tr/timeZoneNames.json';
  import weekData from 'cldr-data/supplemental/weekData.json';

Vue.use(DateRangePickerPlugin);
loadCldr( numberingSystems, gregorian, numbers, timeZoneNames, weekData);

L10n.load({
tr: {
        daterangepicker: {
           placeholder: 'Tarih araligi seciniz',
        }
    }
});

export default {
 data() {
      return {
        minTarih: new Date(),
      }
    }
}
</script>
```
I have read the forum thread at https://www.syncfusion.com/forums/146524/datetimepicker-globalization-example-not-working-typeerror but it did not help me.

Could there be a missing point in the documentation or can you help me to fix this problem.

Best regards,
Erhan Saydam

**Comment by BerlyChristopher** [comment]
Hi Erhansaydam,

Greetings from Syncfusion support. 

We have checked the provided code for DateRangePicker in the Vue CLI 3 application. Unfortunately, the reported issue is not reproduced at our end. But reported issue caused due to **CLDR-data for loaded culture (“tr”) is not loaded properly** in your application. So, we suggest you to kindly ensure that the CLDR-data files for loaded culture are installed and loaded properly in your application.

Please refer to the below attached sample.
**Sample Link**: https://www.syncfusion.com/downloads/support/directtrac/general/ze/DateRangePicker_globalization_vuecli3-759534828 

Also, we will add the information about “how to import CLDR data files in the Vue CLI 3 application” in Volume 1 Main release 2020 which is expected to be rolled out at end of March 2020.

Regards,
Berly B.C

**Comment by erhansaydam** [comment]
Hi Berly Christopher,

Thank you very much for your interest and your sample project. It runs very well. I will check the packages and correct the missing parts.

As you describe it will be so nice to add the information on importing CLDR data files, thereby many others like me can utilize it.

Best regards,
Erhan Saydam
