### ISSUE TITLE
I can't filter Palette Symbols at runtime in Vue Diagram

### ISSUE THREAD

**Issue by erhansaydam** [syncfusion/ej2-vue-ui-components#42]
Hi Syncfusion Team.

I would like to filter palette symbols via user input. I tried many ways but couldn't succeed.

I used a computed array which returns filtered symbols to give the palette as input but didn't recognize.

Then, I used a watcher for user input and filtered the symbols array. Then I have invoked dataBind() of palette instance, it didn't worked neither.

How can I perform it to filter symbols by user input.

Thank you,
Best Regards.

**Comment by KameshRajandran** [comment]
Hi Erhan Saydam,
 
We have created a sample to provide customize searchable boxes in the symbol palette. By using the ‘FilterSymbols’ call back method you can search the symbols in a symbol palette. When you start to search in the symbol palette search box this “FilterSymbols” call back function calls. In that method, by using a palette instance you can get the symbol you want to filter by using symbol id e.g. if the searched word is “Agree” and then you want to display the “Acceptance”  symbol means then in palette symbols, search the Acceptance id symbol and return that symbol. So that the Acceptance symbol gets displayed in the searched result. Please find the below code snippet for how to use filterSymbols method. 

 
Code snippet:

filterSymbols:() => { 
var symbolpalette = this.$refs.symbolpalette.ej2Instances; 
let filterSymbols = []; 
    let text = document.getElementById("textEnter").value; 
     
    if (text === "Agree") { 
      debugger 
      for (let i = 0; i < symbolpalette.palettes.length; i++) { 
        for (let j = 0; j < symbolpalette.palettes[i].symbols.length; j++) { 
          if (symbolpalette.palettes[i].symbols[j].id === "Acceptance") { 
            filterSymbols.push(symbolpalette.palettes[i].symbols[j]); 
          } 
        } 
      } 
    } 
    return filterSymbols; 
      }, 



We have attached a sample for your reference. Please find the sample in below link 
 
Sample: https://www.syncfusion.com/downloads/support/directtrac/275801/ze/Search-Symbols-1373718716 
 
Regards 
Kamesh R.

**Comment by erhansaydam** [comment]
Dear KameshRajandran

Thank you for your deal and project.

The solution does the work, however I would like to remark, this is not proper with the data modelling of Vue.Js. 

As known, to reach and manipulate the values of input, Vue.js uses v-model where the variable is defined in data section of the component. The document.getElementById method does not supply 2 way binding model.

Also with this solution, I have to iterate all of the symbol names with the if statement, which is very unproper.

I tried to solve this problem with Vue.js data model, and succeed it. I will share it soon later, because it is complicated now, and will try to simplify the code to share here.

Thank you for your interest.

Best regards,
Erhan Saydam

**Comment by erhansaydam** [comment]
My solution is as follows:

```
<template>...
<ejs-symbolpalette :palettes='palettes'></ejs-symbolpalette>
...</template>

<script>...
computed: {
      palettes() {
        return [
          {id: "network", expanded: true, symbols: this.filteredSymbols, title: "Symbols"},
        ]
      },
      filteredSymbols() {
        let self = this;
        let searched = this.searched.toLowerCase();
        if (this.searched === '')
          return this.symbols;
        else {
          return self.symbols.filter(function (item) {
            let type = item.addInfo.name.toLowerCase(); //Search symbol by its name under addInfo property (set to symbols data already)
            if (type.includes(searched)) {
              return true;
            }
          });
        }
      }
    },
data: function () {
      return {
        searched: '',
        symbols: [],
        ...
},
created: () {
      this.getSymbols(); //A function to get the symbols from an api
    }
</script>


```

**Comment by Sridhar-Narasimhan** [comment]
Solution provided and closing this issue
