### ISSUE TITLE
Video tag upload

### ISSUE THREAD

**Issue by joshephan** [syncfusion/ej2-vue-ui-components#44]
I tried to use a video tag. 
If I enter HTML directly to add video tags, there is a problem with that area is not selected when editor mode not HTML mode.
How can I using video tag on the editor?

**Comment by Indrajith-Sync** [comment]
Hi @joshephan ,

Greetings from Syncfusion support,

We have validated your reported query. The video tag is not selected since the focus is not maintained. We suggest you to add **<br/>** tag next to video tag addition, so if the content is selected the video tag is considered. We have prepared a sample that tries to meet your requirements.

Sample: https://codesandbox.io/s/vue-template-zg5c4?file=/src/App.vue

Please let us know if the solution helps,

Regards,
Indrajith

**Comment by joshephan** [comment]
@Indrajith-Sync  Thank you for reply. I just add <br> over and under <video> than I can click up and down side of <video>.

**Comment by Indrajith-Sync** [comment]
Hi @joshephan ,

Please let us know if the provided solution, is helpful in resolving the reported issue.

Regards,
Indrajith
