### ISSUE TITLE
Can't use ejs-documenteditor with :value or v-model in Vue.js

### ISSUE THREAD

**Issue by Leozenbergs** [syncfusion/ej2-vue-ui-components#51]
Hi, i'm trying to control the Document Editor text value with the :value and v-model properties, but it's binding is not working. How can i get this value properly?

**Comment by harinichellappa1921** [comment]
Hi @Leozenbergs 

Document Editor component is not a input element to set its value via :value.

To set a value in document editor, you can insert it via insertText API of editor module. please share your requirement on this in detail. So that we can provide solution accordingly.

https://ej2.syncfusion.com/vue/documentation/api/document-editor/editor/#inserttext
 
Sample code snippet
 
//Below code replace or insert the text in current selection

this.$refs.container.ej2Instances.documentEditor.editor.insertText(“Replacing Text”).

You can also import word documents/sfdt in document editor. Kindly refer the below documentation.

https://ej2.syncfusion.com/vue/documentation/document-editor/import/

Regards,

Harini C

**Comment by Leozenbergs** [comment]
Hi @harinichellappa1921 , 
This sample worked as i needed.

Thanks a lot :)
