### ISSUE TITLE
Dinamically change text and value fields in DropDownList component

### ISSUE THREAD

**Issue by Rizzato95** [syncfusion/ej2-vue-ui-components#59]
Hi,
It seems impossible to dinamically change text and value fields in the DropDownList component.
How can I do it?

Here you can find an example:
https://codesandbox.io/s/syncufsion-v18-dropdown-ibwtq?file=/src/App.vue

Thanks.

**Comment by PonmaniMurugaiyan** [comment]
Hi @Rizzato95 ,

We considered the reported issue “**The data source does not change when dynamically changing text and value in the fields property**”as a bug at our end. We will include the fix for the reported issue in the February 24th ,2021 patch release . We appreciate your patience until then.    

     
You can track the status of the reported issue from the below feedback link.    


**Feedback**: https://www.syncfusion.com/feedback/22413/ 


Until then we suggest that you to use the below workaround solution. 


```
onChange: function(e) 
    { 
        this.$refs.dropObj.ej2Instances.fields = { 
        text: e.value, 
        value: e.value, 
      }; 
        this.$refs.dropObj.ej2Instances.dataSource = null; 
        this.$refs.dropObj.ej2Instances.dataSource = this.data; 
        this.$refs.dropObj.ej2Instances.dataBind(); 
    }, 
} 
```

Please find the sample below. 


**Sample link**: https://codesandbox.io/s/syncufsion-v18-dropdown-forked-zpcyz?file=/src/App.vue:919-1224 


Regards, 
Ponmani M

**Comment by SevvandhiN** [comment]
Hi Rizzato95,



Thanks for your patience.

 

We are glad to announce that fix for the issue " The data source does not change when dynamically changing text and value in the fields property " has been rolled out in our weekly nuget release. We request you to update to our latest version "18.4.46".



Please find the sample from the below link.



Sample Link: https://codesandbox.io/s/syncufsion-v18-dropdown-ibwtq?file=/src/App.vue



Package Link: https://www.npmjs.com/package/@syncfusion/ej2-vue-dropdowns/v/18.4.46



Kindly get back to us for further assistance.
 

Regards,

Sevvandhi N

**Comment by Rizzato95** [comment]
Hi @SevvandhiN,

I had already seen and installed the update yesterday. 
Everything works correctly. Thanks.
