### ISSUE TITLE
How to get ExcelFilterBase property from args in actionBegin function?

### ISSUE THREAD

**Issue by meidikawardana** [syncfusion/ej2-vue-ui-components#76]
Hi, I'm using this package `"@syncfusion/ej2-vue-grids": "^19.2.59",`,

And I want solve to this issue in my code:
https://www.syncfusion.com/forums/155673/grid-excel-filter-type-omitting-lots-of-distinct-values

This is my actionBegin `function`:

![image](https://user-images.githubusercontent.com/2024380/134849538-bcf8e01e-4a2b-4a46-95b8-602f4b740d21.png)

so I inspected the `args` parameter in `actionBegin` function. I found out that there is actually a property in `args` object named `filterModel`, and inside `filterModel` there is `itemsCnt` property:

![image](https://user-images.githubusercontent.com/2024380/134849914-ea7d6f71-d267-4a5a-a393-d372ad2c7e18.png)

But I cannot get the `itemsCnt` as you can see in the first image above, it is either undefined or error happened which stops the web app from running properly. It is different than usual javascript object. `filterModel` has a "type" of ExcelFilterBase and I cannot get `filterModel` property because I don't know how to access an  instance of ExcelFilterBase. 

My goal is only to get `itemsCnt` inside the `filterModel` object. how I can do that?

Thanks for any help.

**Comment by rajapandiyan172** [comment]
Hi Meidikawardana, 
 
Thanks for contacting Syncfusion support.

We have validated your query at our end. By default the itemsCnt property is only available in the actionComplete (requestType as filterchoicerequest) event. Because it is calculated based on the response received from the server after the actionBegin event.

actionComplete: https://ej2.syncfusion.com/vue/documentation/api/grid/#actioncomplete

We suggest you to get the itemsCnt value from the actionComplete event. Find the below code example and sample for your reference.

```

    actionComplete: function(args){
       if (args.requestType == 'filterchoicerequest') {
           console.log(args.filterModel.itemsCnt);
       }
    }

```

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/vue_grid_excel_itemscnt587171762.zip

Kindly the share the below details to proceed further on this.

1.	Why you want to use the ItemsCnt value in the actionBegin event?
2.	What is your exact requirement, explain in detail?

Regards, 
Rajapandiyan S
