### ISSUE TITLE
Error when clicking grid pager

### ISSUE THREAD

**Issue by maidmehic** [syncfusion/ej2-vue-ui-components#77]
Hi,

clicking grid pager or horizontal scrollbar when checkbox column is not visible (`:visible="false"`) will throw an error: `RangeError: Maximum call stack size exceeded`

Example: https://codesandbox.io/s/vue-template-forked-m5ko9?file=/src/App.vue

**Comment by BalajiSGrid** [comment]
We already fixed this issue “**_script error thrown while click on pager with checkbox column as invisible state_**” in our 19.3.55 version but you have using 19.3.54 version of Syncfusion grid package since please upgrade the Syncfusion package version then it will overcome the reported issue.

**_Release Notes:_** https://ej2.syncfusion.com/documentation/release-notes/19.3.55/?type=all#grid

_**Sample:**_ https://codesandbox.io/s/vue-template-forked-qxtgpz

**Comment by syncsiva** [comment]
This issue has been resolved. Please feel free to reopen if you have any further queries.
