### ISSUE TITLE
@syncfusion/ej2-vue-inputs - uploader plugin not working

### ISSUE THREAD

**Issue by kberawala** [syncfusion/ej2-vue-ui-components#87]
I am using vue2 and syncfusion plugin version 20.2.36 for uploader plugin

"@syncfusion/ej2-base": "^20.1.61",
"@syncfusion/ej2-buttons": "^20.1.61",
"@syncfusion/ej2-vue-dropdowns": "^20.1.61",
"@syncfusion/ej2-vue-inputs": "^20.1.61",
"@syncfusion/ej2-vue-lists": "^20.1.61",

I am getting below error

[Vue warn]: Failed to mount component: template or render function not defined.
(found in <Root>)

**Comment by Sureshkumar2288** [comment]
Hi Kberawala,

We have validated the reported issue with mentioned packages, but we cannot replicate the reported issue on our end. We have attached the validated sample in the attachment.
If still, you have faced the same issue, then please revert us with the below details. These details will help us to provide an exact solution as earlier as possible.
1.	Whether you have faced the same issue in other component rendering or only uploader component rendering?
2.	Provide your uploader component rendering code example.
3.	If possible, please share the issue replicating sample or replicate the reported issue in the attached sample and revert us with a detailed issue replication procedure with any video or image representation.
Regards,
Sureshkumar P
[Vue2uploader.zip](https://github.com/syncfusion/ej2-vue-ui-components/files/9129907/Vue2uploader.zip)

**Comment by kberawala** [comment]
@Sureshkumar2288 are all packages versions available for use for vue2 ? should we not upgrade to keep the compatibility ?

**Comment by RagunathSF3421** [comment]
Hi Kberawala,


This issue is caused because vue have release a new version for vue 2 i.e.(v2.7.x) in the 1st July 2022. In the newer version of Vue 2.7.x they have introduced some breaking changes which needs to be addressed in the Syncfusion Vue components. So if you install the vue 2.6.14 version, this issue will be resolved.


Make sure that you have not mentioned the cap(^) symbol in the package.json for mentioning the vue version. If you mention cap(^) symbol in the vue version it will install the latest version i.e.(v2.7.x). So please remove the cap(^) symbol or use tilde(~) symbol instead of cap(^) symbol. Please refer the below code snippet for using tidle symbol in the package.json file.

**"vue": "~2.6.14"**


we have planned to add compatibility of Vue components with updated new Vue version and it will be added in our upcoming Volume 3 2022 release, which is scheduled to roll out in the end of September.

You can track the status of this vue 2.7 compatibility from the below feedback link.
https://www.syncfusion.com/feedback/36253/need-to-provide-compatibility-for-syncfusion-components-to-vue-2-7


Regards,
Ragunath S

**Comment by syncsiva** [comment]
Closing for housekeeping purposes. Further, the reported bug can be tracked through below feedback link further,
https://www.syncfusion.com/feedback/36253/need-to-provide-compatibility-for-syncfusion-components-to-vue-2-7
