### ISSUE TITLE
Checkbox :cssClass is not trim white space and crashing "DOMException: DOMTokenList.add: The empty string is not a valid token."

### ISSUE THREAD

**Issue by cesardddp** [syncfusion/ej2-vue-ui-components#94]
Hi!
If a string with a white space in the end of the prop ":cssClass", from Checkbox (ejs-checkbox) API, this will cause the error "DOMException: DOMTokenList.add: The empty string is not a valid token."

i think this can easily fixed with a String.prototype.trim operation, is my actual workaround

**Comment by Yuvan111** [comment]
We have confirmed this as an issue and included the fix for this "CssClass property is not working, if a string with a white space in the end of the property" issue in the weekly patch release (20.4.0.42). So, we suggest you upgrade our Syncfusion packages to our latest version to resolve this issue on your end (20.4.0.42).



Package link: https://www.npmjs.com/package/@syncfusion/ej2-vue-buttons

Release notes:  https://ej2.syncfusion.com/vue/documentation/release-notes/20.4.42/?type=all#checkbox

**Comment by syncsiva** [comment]
This issue has been resolved. Please feel free to reopen if you have any further queries.
